In [3]:
import numpy as np
import pandas as pd

In [4]:
ataques = pd.read_csv('Ataques_num.csv')
ataques

Edad  Genero  Antecedentes familiares  Nivel de estres  Sintomas  \
0         38       0                        0                1         3   
1         51       0                        0                2         4   
2         32       1                        1                2         4   
3         64       1                        0                1         2   
4         31       0                        1                1         4   
...      ...     ...                      ...              ...       ...   
119995    31       1                        1                2         2   
119996    27       0                        0                2         4   
119997    21       1                        0                0         0   
119998    28       0                        0                1         0   
119999    22       1                        0                2         0   

        Severidad  Impacto en la vida  Apoyo social  Nivel de ansiedad  
0               0                   0             2                  1  
1               0                   0             2                  3  
2               0                   2             1                  1  
3               1                   1             2                  2  
4               0                   1             0                  3  
...           ...                 ...           ...                ...  
119995          1                   1             1                  3  
119996          0                   1             2                  3  
119997          1                   2             1                  2  
119998          0                   2             1                  2  
119999          2                   2             0                  4  

[120000 rows x 9 columns]

In [5]:
ataques = ataques.drop('Edad',axis = 1)
ataques

Genero  Antecedentes familiares  Nivel de estres  Sintomas  Severidad  \
0            0                        0                1         3          0   
1            0                        0                2         4          0   
2            1                        1                2         4          0   
3            1                        0                1         2          1   
4            0                        1                1         4          0   
...        ...                      ...              ...       ...        ...   
119995       1                        1                2         2          1   
119996       0                        0                2         4          0   
119997       1                        0                0         0          1   
119998       0                        0                1         0          0   
119999       1                        0                2         0          2   

        Impacto en la vida  Apoyo social  Nivel de ansiedad  
0                        0             2                  1  
1                        0             2                  3  
2                        2             1                  1  
3                        1             2                  2  
4                        1             0                  3  
...                    ...           ...                ...  
119995                   1             1                  3  
119996                   1             2                  3  
119997                   2             1                  2  
119998                   2             1                  2  
119999                   2             0                  4  

[120000 rows x 8 columns]

In [6]:
ataques['Nivel de ansiedad'].value_counts()

Nivel de ansiedad
1    56215
3    39884
2    20523
4     3378
Name: count, dtype: int64

In [7]:
X = ataques.drop('Nivel de ansiedad', axis=1)
y = ataques['Nivel de ansiedad']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
rnd_clf = RandomForestClassifier(n_estimators=100, random_state=42)

In [10]:
rnd_clf.fit(X_test, y_test)

RandomForestClassifier(random_state=42)

In [11]:
y_pred_RFC = rnd_clf.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score

conf_matrixRFC = confusion_matrix(y_test, y_pred_RFC)

# Imprimir la matriz de confusión
print("Matriz de Confusión:")
print(conf_matrixRFC)

Matriz de Confusión:
[[11316     5     0     0]
 [  335  3691   123     0]
 [   52     0  7779     7]
 [    0     0    64   628]]


In [13]:
accuracyConf = accuracy_score(y_test, y_pred_RFC)
print("Precisión (Accuracy): {:.2f}%".format(accuracyConf*100))

Precisión (Accuracy): 97.56%


In [14]:
import numpy as np
import pandas as pd
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Definir la arquitectura de la red neuronal
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

# Compilar el modelo
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/50
3000/3000 [==============================] - 7s 2ms/step - loss: -69682.0781 - accuracy: 0.4676 - val_loss: -249136.1719 - val_accuracy: 0.4717
Epoch 2/50
3000/3000 [==============================] - 5s 2ms/step - loss: -742702.1875 - accuracy: 0.4676 - val_loss: -1393492.2500 - val_accuracy: 0.4717
Epoch 3/50
3000/3000 [==============================] - 5s 2ms/step - loss: -2495708.2500 - accuracy: 0.4676 - val_loss: -3760195.5000 - val_accuracy: 0.4717
Epoch 4/50
3000/3000 [==============================] - 5s 2ms/step - loss: -5653677.5000 - accuracy: 0.4676 - val_loss: -7663461.5000 - val_accuracy: 0.4717
Epoch 5/50
3000/3000 [==============================] - 5s 2ms/step - loss: -10506619.0000 - accuracy: 0.4676 - val_loss: -13403318.0000 - val_accuracy: 0.4717
Epoch 6/50
3000/3000 [==============================] - 6s 2ms/step - loss: -17405492.0000 - accuracy: 0.4676 - val_loss: -21299858.0000 - val_accuracy: 0.4717
Epoch 7/50
3000/3000 [==============================

In [17]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Pérdida:", loss)
print("Precisión:", accuracy)

750/750 [==============================] - 1s 2ms/step - loss: -7151892480.0000 - accuracy: 0.4717
Pérdida: -7151892480.0
Precisión: 0.4717083275318146
